name: "Build executable"
on:
  workflow_dispatch:
  
jobs:
  call-workflow-passing-data:
    uses: VicDeo/go-obfuscate/.github/workflows/test.yml@master

  build:
    env:
      GO_VERSION="1.21.x"
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            GOOS: linux
            artifact: go-obfuscate.linux.amd64 
          - os: windows-latest
            GOOS: windows
            artifact: go-obfuscate.exe 
          - os: macos-latest
            GOOS: darwin
            artifact: go-obfuscate.macos.amd64 
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          
      - name: Install dependencies
        run: go get .
      - name: Build for ${{ matrix.os }}
        run: GOOS="{{ matrix.GOOS }}" GOARCH="amd64" go build -o {{ matrix.artifact }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: go-obfuscate-artifacts
          path: |
            {{ matrix.artifact }}
